# configuration for "master" branch
-
  branches:
    only:
      - master

  version: 6.0.{build}

  configuration:
    - Release

  environment:
    nodejs_version: "6"
    TreatWarningsAsErrors: false

  install:
    - ps: Install-Product node $env:nodejs_version
    - npm install gulp -g
    - npm install

  skip_tags: true

  notifications:
    - provider: GitHubPullRequest
      on_build_success: true
      on_build_failure: true

  cache:
    - packages -> **\packages.config

  before_build:
    - nuget restore siteserver.sln

  after_build:
    - gulp release
    - gulp zip

  artifacts:
    - path: siteserver_install.zip
      name: siteserver_install

  deploy:
    provider: GitHub
    release: siteserver-v$(appveyor_build_version)
    description: 'SiteServer CMS'
    auth_token:
      secure: B/TFrPxGyyTS/NKTQsf/GBLPfGI+Rz/j3e7FVLaP6yjeUDljwkfvV70C+CT34/10
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: false

# configuration for "dev" branch
-
  branches:
    only:
      - dev

  version: 6.0.{build}

  configuration:
    - Release

  environment:
    nodejs_version: "6"
    TreatWarningsAsErrors: false

  install:
    - ps: Install-Product node $env:nodejs_version
    - npm install gulp -g
    - npm install

  skip_tags: true

  notifications:
    - provider: GitHubPullRequest
      on_build_success: true
      on_build_failure: true

  cache:
    - packages -> **\packages.config

  before_build:
    - nuget restore siteserver.sln

  build:
    project: siteserver.sln       # path to Visual Studio solution or project
    publish_nuget: true

  after_build:
    - gulp preview
    - nuget pack build/SiteServer.Update.nuspec
    - gulp zip

  artifacts:
    - path: siteserver_install.zip
      name: siteserver_install
      
    - path: '**\*.nupkg'

  deploy:
    - provider: GitHub
      release: siteserver-v$(appveyor_build_version)-preview
      description: 'SiteServer CMS'
      auth_token:
        secure: B/TFrPxGyyTS/NKTQsf/GBLPfGI+Rz/j3e7FVLaP6yjeUDljwkfvV70C+CT34/10
      artifact: /.*\.zip/
      draft: false
      prerelease: false
      on:
        branch: dev
        appveyor_repo_tag: false

    - provider: NuGet
      server: https://www.myget.org/F/siteserver/api/v2/package                 # remove to push to NuGet.org
      api_key:
        secure: i9vISdFyCeWbRUQw+jhcF748i4oWdeatGBrx+dJ07SDTpt7Hsk9YCRp/ha3ZXfZF
      skip_symbols: false
      symbol_server:           # remove to push symbols to SymbolSource.org
      artifact: /.*\.nupkg/