# configuration for "master" branch
-
  branches:
    only:
      - master

  version: 6.5.{build}
  image: Visual Studio 2017

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.cs'
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration:
    - Release

  environment:
    nodejs_version: "6"
    TreatWarningsAsErrors: false

  install:
    - ps: Install-Product node $env:nodejs_version
    - npm install gulp -g
    - npm install

  skip_tags: true

  cache:
    - packages -> **\packages.config
    - node_modules                        # local npm modules

  before_build:
    - nuget restore siteserver-all.sln

  build:
    project: siteserver-all.sln       # path to Visual Studio solution or project
    publish_nuget: true

  after_build:
    - gulp build
    - nuget pack build/SS.CMS.nuspec
    - gulp zip

  artifacts:
    - path: siteserver_install.zip
      name: siteserver_install

    - path: siteserver.exe
      name: siteserver.exe

    - path: '*.nupkg'

  deploy:
    - provider: GitHub
      release: siteserver-v$(appveyor_build_version)
      description: 'SiteServer CMS'
      auth_token:
        secure: B/TFrPxGyyTS/NKTQsf/GBLPfGI+Rz/j3e7FVLaP6yjeUDljwkfvV70C+CT34/10
      artifact: /.*\.[zip|exe]/
      draft: false
      prerelease: false
      on:
        branch: master
        appveyor_repo_tag: false

    - provider: NuGet
      server:                  # remove to push to NuGet.org
      api_key:
        secure: B9umZPwBVx2TMfYt7G1Eppy7XX0FkqWioXxwR+lKv5XVRc6ezjOXP8D9iuisOWBF
      skip_symbols: false
      symbol_server:           # remove to push symbols to SymbolSource.org
      artifact: /.*\.nupkg/

  notifications:
    - provider: GitHubPullRequest
      on_build_success: true
      on_build_failure: true

# configuration for "dev" branch
-
  branches:
    only:
      - dev

  version: 6.5.{build}-beta
  image: Visual Studio 2017

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.cs'
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  configuration:
    - Release

  environment:
    nodejs_version: "6"
    TreatWarningsAsErrors: false

  install:
    - ps: Install-Product node $env:nodejs_version
    - npm install gulp -g
    - npm install

  skip_tags: true

  cache:
    - packages -> **\packages.config
    - node_modules                        # local npm modules

  before_build:
    - nuget restore siteserver-all.sln

  build:
    project: siteserver-all.sln       # path to Visual Studio solution or project
    publish_nuget: true

  after_build:
    - gulp build
    - nuget pack build/SS.CMS.nuspec
    - gulp zip

  artifacts:
    - path: siteserver_install.zip
      name: siteserver_install

    - path: siteserver.exe
      name: siteserver.exe

    - path: '*.nupkg'

  deploy:
    - provider: GitHub
      release: siteserver-v$(appveyor_build_version)
      description: 'SiteServer CMS'
      auth_token:
        secure: B/TFrPxGyyTS/NKTQsf/GBLPfGI+Rz/j3e7FVLaP6yjeUDljwkfvV70C+CT34/10
      artifact: /.*\.[zip|exe]/
      draft: false
      prerelease: false
      on:
        branch: dev
        appveyor_repo_tag: false

    - provider: NuGet
      server: https://www.myget.org/F/siteserver/api/v2/package                 # remove to push to NuGet.org
      api_key:
        secure: i9vISdFyCeWbRUQw+jhcF748i4oWdeatGBrx+dJ07SDTpt7Hsk9YCRp/ha3ZXfZF
      skip_symbols: false
      symbol_server:           # remove to push symbols to SymbolSource.org
      artifact: /.*\.nupkg/

  notifications:
    - provider: GitHubPullRequest
      on_build_success: true
      on_build_failure: true